import { Product } from "@/entities/product";
import { User } from "@/entities/user";

export const MOCK_USERS: Record<string, User> = {
  u1: {
    id: "u1",
    name: "Rizky Firmansyah",
    username: "rizky",
    email: "rizky@example.com",
    avatar_url: "https://i.pravatar.cc/150?img=11",
    bio: "Vintage collector",
    phone: "08123456789",
    role: "seller",
    is_verified: true,
    seller_rating: 4.8,
    buyer_rating: 5.0,
    total_sales: 124,
    total_purchases: 10,
    created_at: "2023-01-15T10:00:00Z",
    updated_at: "2023-01-15T10:00:00Z"
  },
  u2: {
    id: "u2",
    name: "Sinta Amelia",
    username: "sintaam",
    email: "sinta@example.com",
    avatar_url: "https://i.pravatar.cc/150?img=5",
    bio: "Preloved fashion enthusiast",
    phone: "08123456788",
    role: "seller",
    is_verified: true,
    seller_rating: 4.9,
    buyer_rating: 4.5,
    total_sales: 85,
    total_purchases: 20,
    created_at: "2024-03-22T08:30:00Z",
    updated_at: "2024-03-22T08:30:00Z"
  },
  u3: {
    id: "u3",
    name: "Bagas Pratama",
    username: "bagaspr",
    email: "bagas@example.com",
    avatar_url: "https://i.pravatar.cc/150?img=15",
    bio: null,
    phone: null,
    role: "seller",
    is_verified: false,
    seller_rating: 4.2,
    buyer_rating: 4.0,
    total_sales: 12,
    total_purchases: 5,
    created_at: "2025-06-11T14:20:00Z",
    updated_at: "2025-06-11T14:20:00Z"
  },
  u4: {
    id: "u4",
    name: "Aulia Rahman",
    username: "auliar",
    email: "aulia@example.com",
    avatar_url: "https://i.pravatar.cc/150?img=20",
    bio: null,
    phone: null,
    role: "seller",
    is_verified: true,
    seller_rating: 5.0,
    buyer_rating: 5.0,
    total_sales: 310,
    total_purchases: 50,
    created_at: "2022-11-05T09:12:00Z",
    updated_at: "2022-11-05T09:12:00Z"
  },
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "kemeja-flanel-uniqlo-merah-hitam",
    title: "Kemeja Flanel Uniqlo Merah Hitam Original",
    description: "Kemeja flanel lengan panjang merk Uniqlo, bahan tebal dan hangat. Jarang dipakai, kondisi masih 95% seperti baru.",
    price: 150000,
    condition: "bekas_baik",
    category: "baju",
    size: "L",
    brand: "Uniqlo",
    images: [
      "https://picsum.photos/seed/p1a/600/800",
      "https://picsum.photos/seed/p1b/600/800",
      "https://picsum.photos/seed/p1c/600/800",
      "https://picsum.photos/seed/p1d/600/800",
    ],
    seller: MOCK_USERS["u1"],
    status: "aktif",
    createdAt: "2026-05-20T10:00:00Z",
    wishlistCount: 24,
  },
  {
    id: "p2",
    slug: "jaket-denim-levis-vintage",
    title: "Jaket Denim Levi's Vintage 90s",
    description: "Jaket denim Levi's asli era 90-an. Ada sedikit washed effect alami karena pemakaian. Kancing lengkap.",
    price: 350000,
    condition: "bekas",
    category: "baju",
    size: "M",
    brand: "Levi's",
    images: [
      "https://picsum.photos/seed/p2a/600/800",
      "https://picsum.photos/seed/p2b/600/800",
      "https://picsum.photos/seed/p2c/600/800",
      "https://picsum.photos/seed/p2d/600/800",
    ],
    seller: MOCK_USERS["u2"],
    status: "aktif",
    createdAt: "2026-05-22T14:30:00Z",
    wishlistCount: 56,
  },
  {
    id: "p3",
    slug: "celana-chino-erigo-krem",
    title: "Celana Chino Erigo Premium Krem",
    description: "Celana chino Erigo warna krem. Beli kekecilan belum pernah dipakai ke luar sama sekali. Tag masih ada.",
    price: 120000,
    condition: "baru",
    category: "celana",
    size: "S",
    brand: "Erigo",
    images: [
      "https://picsum.photos/seed/p3a/600/800",
      "https://picsum.photos/seed/p3b/600/800",
      "https://picsum.photos/seed/p3c/600/800",
      "https://picsum.photos/seed/p3d/600/800",
    ],
    seller: MOCK_USERS["u3"],
    status: "aktif",
    createdAt: "2026-05-25T09:15:00Z",
    wishlistCount: 8,
  },
  {
    id: "p4",
    slug: "hoodie-hm-polos-abu",
    title: "Hoodie H&M Polos Abu-abu",
    description: "Hoodie basic H&M warna misty grey. Nyaman untuk daily wear.",
    price: 135000,
    condition: "bekas_baik",
    category: "baju",
    size: "XL",
    brand: "H&M",
    images: [
      "https://picsum.photos/seed/p4a/600/800",
      "https://picsum.photos/seed/p4b/600/800",
      "https://picsum.photos/seed/p4c/600/800",
      "https://picsum.photos/seed/p4d/600/800",
    ],
    seller: MOCK_USERS["u4"],
    status: "aktif",
    createdAt: "2026-05-26T11:45:00Z",
    wishlistCount: 42,
  },
  {
    id: "p5",
    slug: "kaos-oversize-zara-man",
    title: "Kaos Oversize Zara Man Hitam",
    description: "Kaos oversize bahan tebal dari Zara. Kondisi masih sangat bagus tidak belel.",
    price: 90000,
    condition: "bekas_baik",
    category: "baju",
    size: "L",
    brand: "Zara",
    images: [
      "https://picsum.photos/seed/p5a/600/800",
      "https://picsum.photos/seed/p5b/600/800",
      "https://picsum.photos/seed/p5c/600/800",
      "https://picsum.photos/seed/p5d/600/800",
    ],
    seller: MOCK_USERS["u1"],
    status: "aktif",
    createdAt: "2026-05-27T08:20:00Z",
    wishlistCount: 15,
  },
  {
    id: "p6",
    slug: "celana-jeans-stradivarius-mom-fit",
    title: "Stradivarius Mom Fit Jeans Medium Blue",
    description: "Mom fit jeans Stradivarius. Cuttingan bagus banget. Alasan jual: bosan.",
    price: 180000,
    condition: "bekas_baik",
    category: "celana",
    size: "M",
    brand: "Stradivarius",
    images: [
      "https://picsum.photos/seed/p6a/600/800",
      "https://picsum.photos/seed/p6b/600/800",
      "https://picsum.photos/seed/p6c/600/800",
      "https://picsum.photos/seed/p6d/600/800",
    ],
    seller: MOCK_USERS["u2"],
    status: "aktif",
    createdAt: "2026-05-27T15:10:00Z",
    wishlistCount: 31,
  },
  {
    id: "p7",
    slug: "kemeja-kerja-nikicio-hitam",
    title: "Kemeja Nikicio Basic Hitam Lengan Panjang",
    description: "Kemeja formal casual dari Nikicio. Sangat cocok buat ngantor atau hangout. Minus sedikit luntur wajar.",
    price: 210000,
    condition: "bekas",
    category: "baju",
    size: "M",
    brand: "Nikicio",
    images: [
      "https://picsum.photos/seed/p7a/600/800",
      "https://picsum.photos/seed/p7b/600/800",
      "https://picsum.photos/seed/p7c/600/800",
      "https://picsum.photos/seed/p7d/600/800",
    ],
    seller: MOCK_USERS["u4"],
    status: "aktif",
    createdAt: "2026-05-28T10:05:00Z",
    wishlistCount: 19,
  },
  {
    id: "p8",
    slug: "celana-jogger-zara-katun",
    title: "Zara Cotton Jogger Pants Olive",
    description: "Jogger katun warna hijau olive dari Zara. Karet pinggang dan pergelangan kaki masih kencang.",
    price: 160000,
    condition: "bekas_baik",
    category: "celana",
    size: "L",
    brand: "Zara",
    images: [
      "https://picsum.photos/seed/p8a/600/800",
      "https://picsum.photos/seed/p8b/600/800",
      "https://picsum.photos/seed/p8c/600/800",
      "https://picsum.photos/seed/p8d/600/800",
    ],
    seller: MOCK_USERS["u1"],
    status: "aktif",
    createdAt: "2026-05-29T12:00:00Z",
    wishlistCount: 27,
  }
];
